name: CI/CD coverage

on:
  workflow_run:
    workflows: ["CI/CD production"]
    types:
      - completed
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure scripts are executable
        run: chmod +x .github/workflows/scripts/jobs/*.sh

      - name: Lowercase the repo name and project name
        run: .github/workflows/scripts/jobs/format-name.sh

      - name: Build and publish coverage report image
        run: |
          docker build --platform linux/amd64 -t ghcr.io/"${{ env.REPO_LOWER }}"-coverage:${{ github.sha }} -f tools/coverage-report/coverage.Dockerfile .
          docker push ghcr.io/"${{ env.REPO_LOWER }}"-coverage:${{ github.sha }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      STACK_NAME: "coverage"
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure scripts are executable
        run: chmod +x .github/workflows/scripts/jobs/*.sh

      - name: Lowercase the repo name and project name
        run: .github/workflows/scripts/jobs/format-name.sh

      - name: Copy yaml file
        run: |
          cp .github/workflows/stacks/${STACK_NAME}.yml new-${STACK_NAME}.yml

      - name: Update yaml file with last tag
        run: |
          echo "Updating ${{ env.STACK_NAME }}.yml with last image tag."

          sed -i "s|image: ghcr.io/"${{ env.REPO_LOWER }}"-${{ env.STACK_NAME }}:.*|image: ghcr.io/"${{ env.REPO_LOWER }}"-${{ env.STACK_NAME }}:${{ github.sha }}|" new-${{ env.STACK_NAME }}.yml

      - name: Copy updated yaml file to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "new-${{ env.STACK_NAME }}.yml"
          target: "${{ env.PROJECT_LOWER }}"

      - name: Deploy coverage
        uses: appleboy/ssh-action@master
        env:
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          REPO_LOWER: ${{ env.REPO_LOWER }}
          PROJECT_LOWER: ${{ env.PROJECT_LOWER }}
          STACK_NAME: ${{ env.STACK_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOCKER_AUTH,REPO_LOWER,PROJECT_LOWER,STACK_NAME
          script: |
            cd $PROJECT_LOWER

            ./scripts/deployment/deploy.sh

  delete-old-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure scripts are executable
        run: chmod +x .github/workflows/scripts/jobs/*.sh

      - name: Lowercase the repo name and project name
        run: .github/workflows/scripts/jobs/format-name.sh

      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.PROJECT_LOWER }}-coverage
          package-type: 'container'
          min-versions-to-keep: 3
          token: ${{ secrets.GITHUB_TOKEN }}