name: Delete and Recreate Staging Branch

on:
  workflow_run:
    workflows: ["CI/CD production"]
    types:
      - completed
    branches:
      - main

jobs:
  update_staging:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Ensure script is executable
        run: chmod +x .github/workflows/scripts/jobs/recreate-staging.sh

      - name: Delete and recreate staging branch
        run: .github/workflows/scripts/jobs/recreate-staging.sh